name: build_kernel

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  KERNEL_URL: https://github.com/crdroidandroid/android_kernel_xiaomi_msm8996.git
  GCC_ARM64: 
  GCC_ARM: 
  CLANG: https://github.com/yaoxiaonie/clang.git -b 10.0
  GCC_ARM64_TYPE: aarch64-none-linux-gnu
  GCC_ARM_TYPE: arm-none-linux-gnueabihf
  DEFCONFIG_NAME: gemini_defconfig
  BUILD_USER: Actions
  BUILD_HOST: MistyRain
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Free up space
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Installation Required Dependency
         run: |
            sudo apt-get -y update
            sudo apt-get -y install bc bison ca-certificates ccache clang cmake curl file flex gcc g++ git libelf-dev libssl-dev make ninja-build python3 texinfo u-boot-tools xz-utils zlib1g-dev
            sudo apt-get -y install axel

       - name: Clone android kernel source code
         run: |
            sudo git clone $KERNEL_URL kernel
            
       - name: Cloned Android kernel cross-compiler
         run: |
            sudo git clone $CLANG clang
            axel -n 8 "https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz"
            axel -n 8 "https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz"
            tar Jxvf gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz
            tar Jxvf gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz

       
       - name: Start building the Android kernel
         run: |
            sudo curl -sL "https://raw.githubusercontent.com/yaoxiaonie/actions_build_android_kernel/master/build-kernel.sh" > build-kernel.sh
            sudo chmod 777 build-kernel.sh
            sudo bash ./build-kernel.sh "kernel" "${DEFCONFIG_NAME}" "${BUILD_USER}" "${BUILD_HOST}" "${GCC_ARM64_TYPE}" "${GCC_ARM_TYPE}"

       - name: Upload Android kernel (gz)
         uses: actions/upload-artifact@v2
         with:
           name: Image.gz
           path: Image.gz
           if-no-files-found: error

       - name: Upload Android kernel (dtb)
         uses: actions/upload-artifact@v2
         with:
           name: Image.gz-dtb
           path: Image.gz-dtb
           if-no-files-found: error
